---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: admin-serviceaccount
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-serviceaccount
  namespace: default
  annotations:
    kubernetes.io/service-account.name: admin-serviceaccount
type: kubernetes.io/service-account-token
---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
   name: admin-serviceaccount
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: cluster-admin
 subjects:
 - kind: ServiceAccount
   name: admin-serviceaccount
   namespace: default
