name: Build-Korifi-Trinity

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  V_KORIFI: '0.11.2'
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: [ self-hosted ]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        repository: unified-runtime/korifi-trinity
        ref: v${{ env.V_KORIFI }}
        github-server-url: 'https://github.tools.sap'
        token: ${{ KORIFI_TRINITY_TOKEN }}
        path: '.github.tools.sap'


    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    
