name: Publish Release Workflow

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:  
      - name: set version
        run: curl https://github.wdf.sap.corp/status
        id: version
