name: Release Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: [ self-hosted ]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: set version
      run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      id: version

    - name: docker build
      run: VERSION=${{ steps.version.outputs.version }} make docker-build
    - name: docker-push 
      run: VERSION=${{ steps.version.outputs.version }} make docker-push
    
    - name: prepare release artifacts 
      run:  VERSION=${{ steps.version.outputs.version }} make release

    - name: Create the draft release
      env:
        VERSION: ${{ steps.version.outputs.version }}
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh release create "${VERSION}" --draft --notes-file RELEASE.md
    
     - name: Publish Release
       env:
          VERSION: ${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh release edit "${VERSION}" --draft=false --latest

    - name: Upload release artifacts
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh release upload "${VERSION}" "./release-${VERSION}/cfapi-default-cr.yaml"
          gh release upload "${VERSION}" "./release-${VERSION}/cfapi-crd.yaml"
    
    - name: Github release
      uses: actions/create-release@v1
      id: gh_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body_path: RELEASE.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload cfapi crd
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.gh_release.outputs.upload_url }}
        asset_path: ./release-${{ steps.version.outputs.version }}/cfapi-crd.yaml
        asset_name: cfapi-crd.yaml
        asset_content_type: yaml
    - name: upload release default CR yaml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.gh_release.outputs.upload_url }}
        asset_path: ./release-${{ steps.version.outputs.version }}/cfapi-default-cr.yaml
        asset_name: cfapi-default-cr.yaml
        asset_content_type: yaml
    - name: upload release controller yaml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.gh_release.outputs.upload_url }}
        asset_path: ./release-${{ steps.version.outputs.version }}/cfapi-manager.yaml
        asset_name: cfapi-manager.yaml
        asset_content_type: yaml